services:
  - type: web
    name: aooo
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://aooo.onrender.com
      - key: DB_CONNECTION
        value: sqlite
